# Generated by Django 5.1.3 on 2024-11-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
